# See https://pre-commit.com for more information
repos:
  # Go hooks
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c 'gofmt -l -w .'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-imports
        name: goimports
        entry: bash -c 'goimports -l -w .'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: bash -c 'go vet ./...'
        language: system
        types: [go]
        pass_filenames: false

      - id: staticcheck
        name: staticcheck
        entry: bash -c 'staticcheck ./...'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-test
        name: go test
        entry: bash -c 'go test ./...'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy
        entry: bash -c 'go mod tidy && git diff --exit-code go.mod go.sum'
        language: system
        types: [go]
        pass_filenames: false

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
